defmodule DemoWeb.DocsComponents do
  @moduledoc """
  The shell every page under `/docs` is built from: the left nav, and the
  handful of components the pages write their prose with.

  The nav is drawn from two lists. `pages/0` below is the whole of `/docs`,
  in nav order, and each page's own `@sections` is what that page contains.
  A page passes its sections to `docs_layout/1` once and names them again in
  `fetch_section/2` as it renders each heading, so a nav entry and the
  heading it jumps to cannot say different things.

  Pages import this module themselves rather than reaching it through
  `DemoWeb.__using__/1` — `demo_web.ex` is generated by `phx.new` and is not
  part of `examples/overlay`, so it stays untouched.
  """

  use Phoenix.Component

  # Every page under /docs, in the order the nav offers them. The index at
  # /docs lists the same entries, so a page joins both by being added here.
  @pages [
    %{
      id: :data_modeling,
      title: "Data modeling",
      path: "/docs/data-modeling",
      description:
        "The tables FormFlow creates, the graph they hold, and the three ways " <>
          "a graph can be queried."
    }
  ]

  @doc """
  The docs pages, in nav order. `id` is what a page passes as
  `docs_layout/1`'s `current`.
  """
  def pages, do: @pages

  @doc """
  A section from a page's `@sections` list, as attributes for
  `docs_section/1`: `<.docs_section {fetch_section(@sections, "intro")}>`.

  Raises for an id the list does not hold, so a heading the nav does not
  offer never renders.
  """
  def fetch_section(sections, id) do
    Enum.find(sections, &(&1.id == id)) ||
      raise ArgumentError, "no docs section #{inspect(id)} — the nav is built from the same list"
  end

  @doc """
  A docs page: the left nav, and the page's content beside it.

  The nav lists every page under `/docs` and, under the current one, the
  sections `docs_section/1` renders.
  """
  attr :current, :atom, default: nil, doc: "which of `pages/0` is being read, `:index` for /docs"
  attr :sections, :list, default: [], doc: "the current page's sections, in page order"
  slot :inner_block, required: true

  def docs_layout(assigns) do
    ~H"""
    <div class="flex gap-10">
      <nav id="docs-nav" aria-label="Documentation" class="hidden w-56 shrink-0 lg:block">
        <div class="sticky top-8 space-y-2">
          <.link
            navigate="/docs"
            class={[
              "block text-xs font-semibold tracking-wide uppercase",
              (@current == :index && "text-base-content") ||
                "text-base-content/50 hover:text-base-content"
            ]}
          >
            Documentation
          </.link>
          <ul class="space-y-1 text-sm">
            <li :for={page <- pages()}>
              <.link
                navigate={page.path}
                class={[
                  "block rounded px-2 py-1",
                  (page.id == @current && "font-semibold text-base-content") ||
                    "text-base-content/70 hover:bg-base-200 hover:text-base-content"
                ]}
              >
                {page.title}
              </.link>
              <ul
                :if={page.id == @current}
                class="mt-1 mb-2 ml-2 space-y-1 border-l border-base-300 pl-2"
              >
                <li :for={section <- @sections}>
                  <a
                    href={"##{section.id}"}
                    class="block rounded px-2 py-1 text-base-content/70 hover:bg-base-200 hover:text-base-content"
                  >
                    {section.title}
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>

      <div class="min-w-0 flex-1 space-y-10">
        {render_slot(@inner_block)}
      </div>
    </div>

    <style>
      /* An anchored heading lands below the top of the viewport (scroll-mt
         on the headings), and glides rather than snaps */
      @media (prefers-reduced-motion: no-preference) {
        html { scroll-behavior: smooth; }
      }
    </style>
    """
  end

  @doc """
  One section of a docs page, headed by the `<h2>` the nav jumps to.

  Takes a section from the page's list, spread as attributes:
  `<.docs_section {fetch_section(@sections, "intro")}>`.
  """
  attr :id, :string, required: true, doc: "the anchor, and the id the nav links to"
  attr :title, :string, required: true, doc: "the heading, and the nav's label for it"
  slot :aside, doc: "a light note beside the heading"
  slot :inner_block, required: true

  def docs_section(assigns) do
    ~H"""
    <section class="space-y-3">
      <h2 id={@id} class="group scroll-mt-8 mb-6 text-2xl font-semibold">
        {@title}
        <span :if={@aside != []} class="font-light">{render_slot(@aside)}</span>
        <a
          href={"##{@id}"}
          aria-label={"Link to #{@title}"}
          class="ml-1 text-base-content/40 opacity-0 group-hover:opacity-100 focus:opacity-100"
        >
          #
        </a>
      </h2>
      {render_slot(@inner_block)}
    </section>
    """
  end

  @doc "A page's title. One per page, above the sections."
  slot :inner_block, required: true

  def h1(assigns) do
    ~H"""
    <h1 class="text-3xl">{render_slot(@inner_block)}</h1>
    """
  end

  @doc """
  A heading inside a section. Unanchored on purpose: the nav offers
  sections, so only `docs_section/1`'s `<h2>` is a jump target.
  """
  slot :inner_block, required: true

  def h3(assigns) do
    ~H"""
    <h3 class="font-bold mt-6">{render_slot(@inner_block)}</h3>
    """
  end

  @doc "A paragraph, held to a readable measure."
  attr :class, :string, default: nil, doc: "spacing this one paragraph needs"
  slot :inner_block, required: true

  def p(assigns) do
    ~H"""
    <p class={["max-w-3xl", @class]}>{render_slot(@inner_block)}</p>
    """
  end

  @doc """
  An aside in the muted voice — what to take away from the thing above it.
  Newlines in the text are kept, so it can carry paragraphs of its own.
  """
  attr :class, :string, default: nil
  slot :inner_block, required: true

  def note(assigns) do
    ~H"""
    <p class={["max-w-3xl whitespace-pre-line text-base-content/70", @class]}>
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc "A table that scrolls inside its own box rather than stretching the page."
  attr :id, :string, required: true
  attr :class, :string, default: nil, doc: "spacing the wrapper needs"
  slot :inner_block, required: true

  def docs_table(assigns) do
    ~H"""
    <div class={["overflow-x-auto", @class]}>
      <table id={@id} class="table table-sm">
        {render_slot(@inner_block)}
      </table>
    </div>
    """
  end
end
